name: Publish Package to npmjs
# src: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      # I am too lazy to do anything special to push to npm.
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"
        # Increase patch version and commit*(yes it commits as well)
      - run: npm version patch

        # src: 
      - name: Push
        run: |
          git remote set-url --push origin https://sahilrajput03:$GITHUB_TOKEN@github.com/sahilrajput03/flash-runner-npm
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
